---
- hosts: all
  become: yes

  tasks:
    - name: Set firewall default policy
      ufw: state=enabled policy=reject

    - name: Allow ssh access
      ufw: rule=allow port=22

    - name: Prevent brute force attacks
      ufw: rule=limit port=ssh proto=tcp

    - name: Allow http access
      ufw: rule=allow port=80

    - name: Allow https access
      ufw: rule=allow port=443

